#!/usr/bin/env node

// Fix for large files generation
// once https://github.com/timostamm/protobuf-ts/pull/135 is merged
// we can remove this 2 lines as they'll be part of the plugin framework
if (process.stdout._handle) {
    process.stdout._handle.setBlocking(true);
}

require('./build/protoc-gen-twirp-ts/plugin');
