openapi: 3.0.3
info:
  title: Haberdasher
  version: 1.0.0
  description: Haberdasher service makes hats for clients.
paths:
  /twirp.example.haberdasher.Haberdasher/MakeHat:
    post:
      summary: MakeHat produces a hat of mysterious, randomly-selected color!
      operationId: Haberdasher_MakeHat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Size"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hat"
  /twirp.example.haberdasher.Haberdasher/FindHat:
    post:
      summary: ""
      operationId: Haberdasher_FindHat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FindHatRPC"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindHatRPC"
  /twirp.example.haberdasher.Haberdasher/ListHat:
    post:
      summary: ""
      operationId: Haberdasher_ListHat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListHatRPC"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListHatRPC"
components:
  schemas:
    Size:
      properties:
        inches:
          type: integer
          description: must be > 0
      description: Size of a Hat, in inches.
    Hat:
      properties:
        id:
          type: string
          description: ""
        inches:
          type: integer
          description: ""
        color:
          type: string
          description: anything but "invisible"
        name:
          type: string
          description: i.e. "bowler"
        variants:
          type: array
          items:
            $ref: "#/components/schemas/Hat"
          description: ""
      description: A Hat is a piece of headwear made by a Haberdasher.
    FindHatRPC:
      properties:
        hat_id:
          type: string
          description: ""
      description: ""
    ListHatRPC:
      properties:
        filters:
          type: array
          items:
            $ref: "#/components/schemas/Filter"
          description: ""
      description: ""
    Filter:
      properties:
        order_by:
          type: string
          description: ""
        pagination:
          $ref: "#/components/schemas/Pagination"
      description: ""
    Pagination:
      properties:
        limit:
          type: integer
          description: ""
        offset:
          type: integer
          description: ""
      description: ""
